# Generated by Django 3.2.12 on 2022-03-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0159_deprecate_inventory_source_UoPU_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedjob',
            name='notifications_processed',
            field=models.BooleanField(
                default=False, editable=False, help_text='If True, the dispatcher has processed success or failure notifications for this job.'
            ),
        ),
    ]
