# Generated by Django 3.2.13 on 2022-05-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0162_alter_unifiedjob_dependent_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unifiedjob',
            name='host_status_counts',
        ),
        migrations.AddField(
            model_name='unifiedjob',
            name='event_processing_finished',
            field=models.BooleanField(
                default=False, editable=False, help_text='Indicates whether all of the events generated by this unified job have been saved to the database.'
            ),
        ),
    ]
