# Generated by Django 4.2 on 2023-06-12 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0184_django_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhoccommandevent',
            name='host',
            field=models.ForeignKey(
                db_constraint=False,
                db_index=False,
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='ad_hoc_command_events',
                to='main.host',
            ),
        ),
        migrations.AlterField(
            model_name='adhoccommandevent',
            name='modified',
            field=models.DateTimeField(default=None, editable=False),
        ),
        migrations.AlterField(
            model_name='inventoryupdateevent',
            name='modified',
            field=models.DateTimeField(default=None, editable=False),
        ),
        migrations.AlterField(
            model_name='jobevent',
            name='host',
            field=models.ForeignKey(
                db_constraint=False,
                db_index=False,
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='job_events_as_primary_host',
                to='main.host',
            ),
        ),
        migrations.AlterField(
            model_name='jobevent',
            name='modified',
            field=models.DateTimeField(default=None, editable=False),
        ),
        migrations.AlterField(
            model_name='projectupdateevent',
            name='modified',
            field=models.DateTimeField(default=None, editable=False),
        ),
        migrations.AlterField(
            model_name='systemjobevent',
            name='modified',
            field=models.DateTimeField(default=None, editable=False),
        ),
        migrations.AddIndex(
            model_name='adhoccommandevent',
            index=models.Index(fields=['ad_hoc_command', 'job_created', 'host_id'], name='main_adhocc_ad_hoc__141bc1_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryupdateevent',
            index=models.Index(fields=['inventory_update', 'job_created', 'modified'], name='main_invent_invento_b5bbb9_idx'),
        ),
        migrations.AddIndex(
            model_name='jobevent',
            index=models.Index(fields=['job', 'job_created', 'host_id'], name='main_jobeve_job_id_958dd4_idx'),
        ),
        migrations.AddIndex(
            model_name='jobevent',
            index=models.Index(fields=['job', 'job_created', 'modified'], name='main_jobeve_job_id_132b0b_idx'),
        ),
        migrations.AddIndex(
            model_name='projectupdateevent',
            index=models.Index(fields=['project_update', 'job_created', 'modified'], name='main_projec_project_882c4f_idx'),
        ),
        migrations.AddIndex(
            model_name='systemjobevent',
            index=models.Index(fields=['system_job', 'job_created', 'modified'], name='main_system_system__a767d9_idx'),
        ),
    ]
