# Generated by Django 4.2.6 on 2024-01-04 15:15

import logging

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


logger = logging.getLogger(__name__)


def migrate_to_new_user_model(apps, schema_editor):
    old_user = apps.get_model('auth', 'User')
    new_user = apps.get_model('main', 'User')
    Role = apps.get_model('main', 'Role')
    auditor_role = Role.objects.get(singleton_name='system_auditor')
    auditor_ids = set(auditor_role.members.values_list('id', flat=True))
    old_fields = [f.name for f in old_user._meta.concrete_fields]
    for ct, old_u in enumerate(old_user.objects.all(), 1):
        new_u = new_user(**{k: getattr(old_u, k) for k in old_fields})
        if old_u.id in auditor_ids:
            new_u.is_system_auditor = True
        new_u.save()
    if ct:
        logger.info(f'Migrated {ct} users to new User model')
    # TODO: also migrate relationships from auth.User to main.User
    # User.objects.first()._meta.get_all_related_objects()
    # User.objects.first()._meta.get_all_related_many_to_many_objects()
    # TODO: delete records in the old auth.User table


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0187_hop_nodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                (
                    'is_superuser',
                    models.BooleanField(
                        default=False,
                        help_text='Designates that this user has all permissions without explicitly assigning them.',
                        verbose_name='superuser status',
                    ),
                ),
                (
                    'username',
                    models.CharField(
                        error_messages={'unique': 'A user with that username already exists.'},
                        help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name='username',
                    ),
                ),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                (
                    'is_staff',
                    models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=True,
                        help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.',
                        verbose_name='active',
                    ),
                ),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_system_auditor', models.BooleanField(default=False)),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RunPython(migrate_to_new_user_model, migrations.RunPython.noop),
    ]
