# Generated by Django 4.2.6 on 2023-11-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0188_add_django_permissions'),
    ]
    run_before = [
        ('ansible_base', '0010_RBAC'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_system_auditor',
            field=models.BooleanField(default=False, help_text='Can view everying in the system, proxies to User model'),
        ),
    ]
